# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "556480f69de683393f6d842d6392af62"
name = "profile-editor-app"
handle = "profile-editor-app"
application_url = "https://reliability-attachments-distinction-gpl.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers"

[auth]
redirect_urls = [
  "https://reliability-attachments-distinction-gpl.trycloudflare.com/auth/callback",
  "https://reliability-attachments-distinction-gpl.trycloudflare.com/auth/shopify/callback",
  "https://reliability-attachments-distinction-gpl.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://reliability-attachments-distinction-gpl.trycloudflare.com"
subpath = "om-profile-editor"
prefix = "apps"

[pos]
embedded = false
