# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "628344578bd9fda25e03a69def199006"
application_url = "https://architecture-barbie-garden-contributing.trycloudflare.com"
embedded = true
name = "profile-editor-app"
handle = "profile-editor-app-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers"

[auth]
redirect_urls = [
  "https://architecture-barbie-garden-contributing.trycloudflare.com/auth/callback",
  "https://architecture-barbie-garden-contributing.trycloudflare.com/auth/shopify/callback",
  "https://architecture-barbie-garden-contributing.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://architecture-barbie-garden-contributing.trycloudflare.com"
subpath = "om-profile-editor"
prefix = "apps"

[pos]
embedded = false
